name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
          msbuild-architecture: x64

      - name: Set configuration
        run: msbuild /p:Configuration=Release
      - name: Build and run CompressShaders
        run: |
          cd Tools/CompressShaders
          dotnet build
          dotnet run
      - name: Build Whisper project
        run: |
          msbuild Whisper/Whisper.sln /p:Configuration=Release
      - name: Set runtime library to Multi-threaded DLL
        run: |
          msbuild Whisper/Whisper.sln /p:Configuration=Release /p:RuntimeLibrary=MD
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyArtifact
          path: Whisper/
